name: "Bug Report"
description: "Create a report to help us improve. Something is broken or not working as expected."
title: "[BUG] - "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report. Please be as detailed as possible.

  - type: dropdown
    id: component
    attributes:
      label: "Affected Component"
      description: "Which part of the ScoutX platform is this bug in?"
      multiple: false
      options:
        - "Backend / API"
        - "ScoutX Dashboard (Players, Parents, Coaches)"
        - "ScoutX Pro Dashboard (Pro Admins)"
        - "ScoutX Flutter App (Players, Academies)"
        - "ScoutX Pro Flutter App (Scouts)"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "A clear and concise description of what the bug is."
      placeholder: "When I click the 'Save Profile' button, the page crashes."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Please provide the exact steps to reproduce this bug."
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "A clear and concise description of what you expected to happen."
      placeholder: "The profile should save successfully and I should see a confirmation message."
    validations:
      required: true

  - type: textarea
    id: media
    attributes:
      label: "Screenshots or Videos"
      description: "If applicable, please add screenshots or a screen recording (Loom, etc.) to help explain your problem. You can drag and drop files here."
