name: "Feature Request"
description: "Suggest an idea for a new feature or an enhancement to an existing one."
title: "[FEAT] - "
labels: ["feature-request"]
body:
  - type: markdown
    attributes:
      value: "Thank you for suggesting a new feature! Please provide as much context as possible."

  - type: dropdown
    id: component
    attributes:
      label: "Related Component"
      description: "Which part of the ScoutX platform would this feature affect?"
      multiple: false
      options:
        - "Backend / API"
        - "ScoutX Dashboard (Players, Parents, Coaches)"
        - "ScoutX Pro Dashboard (Pro Admins)"
        - "ScoutX Flutter App (Players, Academies)"
        - "ScoutX Pro Flutter App (Scouts)"
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: "Is your feature request related to a problem? Please describe."
      description: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
      placeholder: "It's difficult for coaches to see a summary of a player's recent activity at a glance."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen."
      placeholder: "I'd like a new 'Activity Summary' widget on the player profile page that shows their last 5 logged activities."
    validations:
      required: true

  - type: textarea
    id: audience
    attributes:
      label: "Who is this for?"
      description: "Who are the primary users that would benefit from this feature?"
      placeholder: "e.g., Coaches, Pro Admins, Players"

  - type: textarea
    id: context
    attributes:
      label: "Additional context"
      description: "Add any other context, mockups, or links about the feature request here. You can drag and drop images."
